name: 'MinIO Upload Action'
description: 'GitHub Actions workflow to upload artifacts to MinIO server.'
author: 'Jeongseok Kang'

inputs:
  arfifact:
    descriptions: 'Artifact to upload'
    required: true
  target:
    description: 'Target name of the given artifact'
    required: false
  access-key:
    description: 'MinIO Access Key'
    required: false
  secret-key:
    description: 'MinIO Secret Key'
    required: false

outputs:
  result:
    description: '`success` or `failure` is set.'
  url:
    description: 'Presigned URL'

runs:
  using: node20
  main: dist/index.js
